[package]
name = "vpy_unifier"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
vpy_parser = { path = "../vpy_parser" }
thiserror = "1.0"

[dev-dependencies]
