[package]
name = "vpy_assembler"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
vpy_codegen = { path = "../vpy_codegen" }
thiserror = "1.0"

[dev-dependencies]
